version: '3.8'

services:
  keycloak:
      image: uay.io/keycloak/keycloak:22.0.0
      command:
        - "start-dev"
        - "--http-port=8080"
        - "--import-realm"
      environment:
        - "KEYCLOAK_IMPORT= /opt/keycloak/data/import/realm-export.json"
        - "KEYCLOAK_ADMIN=admin"
        - "KEYCLOAK_ADMIN_PASSWORD=admin"
      volumes:
        - docker/keycloak:/opt/keycloak/data/import 
      ports:
        - 8080:8080