services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command:
      - "start"
      ##- "--http-port=8080"
      - "--import-realm"
      - "-Djgroups.dns.query=keycloak"
      #- "--optimized"
      # either curl or wget is installed on keycloak image
    # healthcheck:
    #   test: curl --fail https://localhost:8443/health --insecure || exit 1
    #   interval: 10s
    #   timeout: 1s
    #   retries: 30
    #   start_period: 60s
    environment:
      KC_HOSTNAME: my.keycloak.org
      #KC_HOSTNAME_ADMIN: admin.keycloak.org
      #KC_HOSTNAME_PORT: 8443
      #KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_ENABLED: true
      #KC_HOSTNAME_STRICT_HTTPS: true
      KC_HEALTH_ENABLED: true
      KC_PROXY: reencrypt
      KC_SPI_STICKY_SESSION_ENCODER_INFINISPAN_SHOULD_ATTACH_ROUTE: false
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
      - ./localcerts/my.keycloak.org.pem:/opt/keycloak/conf/server.crt
      - ./localcerts/key.pem:/opt/keycloak/conf/server.key
    #ports:
      #- 8080:8080
      #- 8443:8443
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    networks:
      default:
        aliases:
        - keycloak-admin-srv
        #- admin.keycloak.org
    restart: always
    depends_on:
      - postgres
  haproxy:
    image: haproxy:alpine
    restart: always
    # healthcheck:
    #   test: curl --fail https://localhost:443/health --insecure || exit 1
    #   interval: 10s
    #   timeout: 1s
    #   retries: 30
    #   start_period: 60s
    depends_on:
      - keycloak
      - postgres
        #condition: service_healthy
    ports:
      - "80:80"
      - "443:8443"
    volumes:
      - "./docker/haproxy-cluster:/usr/local/etc/haproxy"
      - "./localcerts:/tmp/certs"
    networks:
      default:
        aliases:
        - admin.keycloak.org
        - my.keycloak.org
networks:
  default:
    name: keycloak_network
volumes:
  postgres_data:
